### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by HUuxiaobin** [ArmastusChen/total_selfie#1]
thanks for your great work! I am wondering when you will  release the training set. looking forward for your reply.

**Comment by HUuxiaobin** [comment]
@ArmastusChen

**Comment by ArmastusChen** [comment]
Hi @HUuxiaobin,

Thank you for your interest. Please check out the link to training set below and let me know if you have any question:

https://drive.google.com/file/d/1T6FEl_4zwOJ5RQRjL1bPT63w8ESKnl_x/view?usp=drive_link
