### ISSUE TITLE
where is your pretrained model

### ISSUE THREAD

**Issue by leoriczhang** [ArmastusChen/total_selfie#2]
Hi，
    I really appreciate your work，but when I try to use your demo，I cant find 00000196-checkpoint.pth.tar and pretrained_weights/selfie_conditioned_inpainting/pbe_selfie2full and pretrained_weights/seg/model_final.pth   . Only model_mlp_modified4_vae20000.ckpt in your Google Pretrained_models

**Comment by ArmastusChen** [comment]
Thanks for your interest in our work.  Please refer to the README and download the pretrained model using this link.

https://drive.google.com/drive/folders/1U0-MJVbcdBWvMvBMY8cI7NJDX6njXmow?usp=drive_link

**Comment by leoriczhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
已收到！
